-- admin/admin calculated by https://bcrypt-generator.com/
INSERT INTO PERSON (USERNAME, PASSWORD, ROLE) VALUES ('admin', '$2a$12$jYJYfiKpP7QRK9nCg9E9ueoHB0vg546SyvgHAeLpGIESaNXg734JO', 'ADMIN');
INSERT INTO PERSON (USERNAME, PASSWORD, ROLE) VALUES ('user1', '$2a$12$EOeIyL4HLzmRulC5kOsXUumJ85plSbNjLRDySMk3C7CGJqwtd3OC2', 'USER');
INSERT INTO CONTACT (ADDRESS, NAME, PHONE_NUMBER) VALUES ('contact1', 'john', '12345678');
INSERT INTO CONTACT (ADDRESS, NAME, PHONE_NUMBER) VALUES ('contact2', 'Doe', '12345678');